[build]
  # Build command
  command = "./build.sh"
  
  # Directory ที่จะ serve static files
  publish = "public"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Environment variables สำหรับ build
  NODE_ENV = "production"

# Netlify Functions สำหรับ API endpoints
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# Serve static files for documentation
[[redirects]]
  from = "/docs/*"
  to = "/courses/:splat"
  status = 200

# SPA fallback สำหรับหน้าแรก
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers สำหรับ CORS และ security
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/docs/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-ancestors 'self'"

# Environment variables สำหรับ production
[context.production.environment]
  BASE_URL = "$URL"
  NODE_ENV = "production"
  JWT_SECRET = "your-secure-jwt-secret-for-production"
  PORT = "8888"
  HOST = "0.0.0.0"

# Environment variables สำหรับ branch previews
[context.branch-deploy.environment]
  BASE_URL = "$DEPLOY_PRIME_URL"
  NODE_ENV = "staging"
  JWT_SECRET = "staging-jwt-secret"